name: easy_colors
description: A Flutter package to manage custom colors used in the project
version: 0.0.1+1
homepage: https://github.com/Supercaly/easy_colors
repository: https://github.com/Supercaly/easy_colors
issue_tracker: https://github.com/Supercaly/easy_colors/issues

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  args: ^1.6.0
  path: ^1.7.0
  code_builder: ^3.5.0
  dart_style: ^1.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: